server:
  # 服务端口
  port: 9090
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare: 30
dt:
  dir : 'd:/face/'
  suffix : 'face.jpg'
  polices : '22,23,23,4,6'

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://32.33.63.42:3306/face?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
#    username: dev
#    password: dev123456
    url: jdbc:mysql://localhost:3306/face?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    username: dev
    password: dev123456
#    url: jdbc:mysql://localhost:3306/face?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
    #    type: com.alibaba.druid.pool.DruidDataSource
    # 从库数据源
    # 初始连接数
    initial-size: 10
    # 最大连接池数量
    max-active: 100
    # 最小连接池数量
    min-idle: 10
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    stat-view-servlet:
      enabled: true
      url-pattern: /monitor/druid/*
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: false
      wall:
        config:
          multi-statement-allow: true
mybatis-plus:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tuhui
  global-config:
    # 刷新mapper 调试神器
    refresh-mapper: true
    #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
    id-type: AUTO
    #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
    field-strategy: not_empty
    #驼峰下划线转换
    column-underline: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    db-type: h2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: 'null'
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Halo平台配置
halo:
  app_code: 4e8439ce-af50-400f-a02e-ac23005f27c7
  app_key: 3487315dd814caff3acb90b0ca1bbbbe
  app_secret: 8bbedb605ac4101cbaf5e3089c5123a0a9ae85b6
  grant_type: client_credential
  openOrgDomain: NgQqQiNPIA1nFHMSP1E7R3MWLhopEHMWO1o8CTkUIBAgRmsKOghtQCFCcENzQ3YQIhV2QQ
